remote_theme: just-the-docs/just-the-docs
title: Federal Sigstore Blueprint
description: Zero Trust Supply Chain Security for Federal Linux Clusters
aux_links:
  "View on GitHub": [https://github.com/saisravan909/fed-sigstore-blueprint-zero-trust-linux](https://github.com/saisravan909/fed-sigstore-blueprint-zero-trust-linux)
